#ifndef __MY_DEBUG_H
#define __MY_DEBUG_H

#define __DEBUG__ 

// #ifdef __DEBUG__  
// #define DEBUG(format,...) printf("File: "__FILE__", Line: %05d: "format"\r\n", __LINE__, ##__VA_ARGS__)  
// #else  
// #define DEBUG(format,...)	((void)0)  
// #endif 

#ifdef __DEBUG__ 
//	#define	DEBUG_TIMER
// 	#define DEBUG_CMD
// 	#define DEBUG_LINK
// 	#define DEBUG_USB
//	#define DEBUG_LINK_MODE
//	#define DEBUG_SPEED
//	#define DEBUG_SAMPLE_KY
//	#define DEBUG_SAMPLE_KZ	
//	#define DEBUG_FORCE_KY
//	#define DEBUG_FORCE_KZ
//	#define DEBUG_COORDINATE_DRAW_LINE
//	#define DEBUG_HARD_TEST
//	#define DEBUG_TEST_LOAD
//	#define	REAL_TIME_DATA_FRAM
#endif

#endif
